### ISSUE TITLE
Implemenation for Ketton in PyTorch

### ISSUE THREAD

**Issue by dashafok** [LukasMosser/PorousMediaGan#8]
Hi!

I am trying to reproduce the results of the paper. 
Did you implement the architecture for Ketton and Beadpack in PyTorch? I have modified the code for Berea: removed label smoothing and added noise to discriminator inputs. The best result I could achieve for Ketton:

![ketton_porousgan_1](https://user-images.githubusercontent.com/22776958/58886587-d7a79a00-86ec-11e9-894a-c78ec6d30287.png)

Maybe you know, what I could have done wrong?

Thank you.

**Comment by LukasMosser** [comment]
One thing you probably should try is plotting a section through the middle.
This looks like it could be from the edges. 
Due to the edge effects in transposed convolutions, you'll see artefacts at the border.

What metrics are you using to just whether your images is "good"?
Porosity? Two-point correlations? Flow properties?

**Comment by dashafok** [comment]
Yes, this is border artefacts, thank you!

**Comment by LukasMosser** [comment]
Great! Glad I could help, all the best!
